Mon 20969 - have the possibility to invert filters accepted hostgroups rejected hostgroups
centreon/centreon-stream-connector-scripts pull request #158
Opened 2023-10-04 18:57 UTC by sdepassio

2023-10-09 14:26 UTC, lucie-dubrunfaut commented on modules/centreon-stream-connectors-lib/sc_event.lua
> +  if (not accepted_hostgroups_isnotempty and not rejected_hostgroups_isnotempty) or (accepted_hostgroups_isnotempty and rejected_hostgroups_isnotempty) then
I'm not sure but you are checking if : 
- only accepted hostgroup is set
- accepted host group and rejected host group are set together
but not if only rejected host group is set ?
Don't user may needs to only set rejected host group ?

2023-10-31 13:19 UTC, tanguyvda requested changes

2023-10-31 13:19 UTC, tanguyvda commented on modules/centreon-stream-connectors-lib/sc_event.lua
> +-- @return bv_name (string) the name of the first matching BV
```suggestion
-- @param bvs_list (string) a coma separated list of BV name
-- @return bv_name (string) the name of the first matching BV
```

2023-10-31 13:19 UTC, tanguyvda commented on modules/centreon-stream-connectors-lib/sc_event.lua
> +-- @return poller_name or false (string|boolean) the name of the first matching poller if found or false if not found
```suggestion
-- @param pollers_list (string) a coma separated list of poller name
-- @return poller_name or false (string|boolean) the name of the first matching poller if found or false if not found
```

2023-10-31 13:19 UTC, tanguyvda commented on modules/centreon-stream-connectors-lib/sc_event.lua
>  -- @return accepted_alias or false (string|boolean) the alias of the first matching author if found or false if not found
```suggestion
-- @param authors_list (string) a coma separeted list of author name
-- @return accepted_alias or false (string|boolean) the alias of the first matching author if found or false if not found
```

2023-10-31 13:19 UTC, tanguyvda commented on modules/centreon-stream-connectors-lib/sc_event.lua
> +-- @return hostgroup_name (string) the name of the first matching hostgroup
```suggestion
-- @param hostgroups_list (string) a coma separated list of hostgroup name
-- @return hostgroup_name (string) the name of the first matching hostgroup
```

2023-10-31 13:19 UTC, tanguyvda commented on modules/centreon-stream-connectors-lib/sc_event.lua
> +-- @return servicegroup_name or false (string|boolean) the name of the first matching servicegroup if found or false if not found
```suggestion
-- @param servicegroups_list (string) a coma separated list of servicegroup name
-- @return servicegroup_name or false (string|boolean) the name of the first matching servicegroup if found or false if not found
```

2023-10-31 13:19 UTC, tanguyvda commented on modules/docs/sc_event.md
> +| a list of hostgroups | string | no       |               |
```suggestion
| a coma separated list of hostgroups | string | no       |               |
```

2023-10-31 13:19 UTC, tanguyvda commented on modules/docs/sc_event.md
> +| a list of hostgroups | string | no       |               |
don't mind the fucked up indentation, it'll be fixed when we update the doc from code editor

2023-10-31 13:19 UTC, tanguyvda commented on modules/docs/sc_event.md
> +| a list of servicegroups | string | no       |               |
```suggestion
| a coma separated list of servicegroups | string | no       |               |
```

2023-10-31 13:19 UTC, tanguyvda commented on modules/docs/sc_event.md
> +| a list of bvs | string | no       |               |
```suggestion
| a coma separated list of bvs | string | no       |               |
```

2023-10-31 13:19 UTC, tanguyvda commented on modules/docs/sc_event.md
> +| a list of pollers | string | no       |               |
```suggestion
| a coma separated list of pollers | string | no       |               |
```

2023-10-31 13:19 UTC, tanguyvda commented on modules/docs/sc_event.md
> +| a list of authors | string | no       |               |
```suggestion
| a coma separated list of authors | string | no       |               |
```

2023-11-08 08:48 UTC, tanguyvda approved these changes

2023-11-08 09:16 UTC, lucie-dubrunfaut approved these changes

2023-11-08 13:15 UTC, merged