Infra 1576 keep connector
centreon/centreon-stream-connector-scripts pull request #248
Opened 2024-12-16 14:47 UTC by guillaumemel

## Description

This pull request introduces a stream connector compatible with the product [KEEP](https://www.keephq.dev/).

The purpose of this change is to enable seamless integration between Centreon and KEEP by adding support for KEEP's incoming webhooks.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [X] 24.10.x
- [ ] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

1. Create a Trial or Self-Hosted Environment on KEEP:
Set up a trial account on KEEP (SaaS) or deploy a self-hosted environment.
2. Retrieve the API Key:
In the KEEP environment, go to settings and retrieve the API key for incoming webhooks.
3. Configure a Generic Stream Connector in Centreon:
Add a stream connector with the following parameters:
keep_api_key → Corresponds to your KEEP API key.
http_server_url → (Optional) For self-hosted URLs. Not required for KEEP SaaS.

![image](https://github.com/user-attachments/assets/664c3ca5-ab75-43f5-9bf0-a49cd3497929)
4. Test the Integration:
Trigger events in Centreon and ensure that they are properly processed and displayed in KEEP.

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-12-18 13:19 UTC, tanguyvda requested changes

2024-12-18 13:19 UTC, tanguyvda commented on centreon-certified/keep/keep-events-apiv2.lua
> +      broker_log:info(3, "write: " .. event.host_id .. "_" .. (event.service_id or "H") .. " Scheduled downtime. Dropping.")
```suggestion
      queue.sc_logger:debug("write: " .. event.host_id .. "_" .. (event.service_id or "H") .. " Scheduled downtime. Dropping.")
```

2024-12-18 16:46 UTC, gmelon-centreon reviewed
Thank you Tanguy

2025-02-24 18:43 UTC, tanguyvda approved these changes

2025-03-06 10:52 UTC, lucie-dubrunfaut approved these changes

2025-04-28 14:57 UTC, merged